//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    using System.ComponentModel.DataAnnotations;
    public partial class NGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NGroup()
        {
            this.NGroupMemberTeachers = new HashSet<NGroupMemberTeacher1>();
            this.NGroupMessages = new HashSet<NGroupMessage>();
            this.NGroupMessageTeachers = new HashSet<NGroupMessageTeacher1>();
        }
    
        public int GroupID { get; set; }
        public string GroupName { get; set; }
        public byte[] GroupIcon { get; set; }
        public string classID { get; set; }
        public string subID { get; set; }
        [Required]
        [Display(Name = "Select File")]
        [DataType(DataType.Upload)]
        public HttpPostedFileBase files { get; set; }
        public virtual Class Class { get; set; }
        public virtual Subject Subject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NGroupMemberTeacher1> NGroupMemberTeachers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NGroupMessage> NGroupMessages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NGroupMessageTeacher1> NGroupMessageTeachers { get; set; }
    }
}
