//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject_Has_Module
    {
        public string SMRating { get; set; }
        public string ModuleID { get; set; }
        public string SubID { get; set; }
    
        public virtual Module Module { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
